// ==========--: Includes :--========== //

// GLAD is a library that provides access to OpenGL API.
#include <glad/glad.h>

// SFML is a "multi-media application" Library.
// It facilititates the creation of the window for us,
// and receiving input events such us keyboard presses, mouse clicks/movements.

#include <SFML/Window.hpp>
#include <SFML/OpenGL.hpp>

// Standard C++ libraries we're using.
#include <iostream>

// Header files.
#include "lab-utils/application.hpp"

// ==========--: Main Application Class :--========== //

namespace LabUtils
{
	LabApplication::LabApplication() {}

	void LabApplication::initializeWindowAndGraphics(sf::Vector2u windowSize, const sf::String windowTitle)
	{
		// Tell SFML the graphics settings we want:
		sf::ContextSettings contextSettings;
		contextSettings.depthBits = 24;
		// Use OpenGL 3.3 ↓
		contextSettings.majorVersion = 3;
		contextSettings.minorVersion = 3;
		// With compatibility profile ↓
		contextSettings.attributeFlags = sf::ContextSettings::Attribute::Default;

		window.create(
			sf::VideoMode(windowSize), windowTitle,
			sf::Style::Default, sf::State::Windowed,
			contextSettings
		);
		window.setVerticalSyncEnabled(true); // Enable VSync.

		// Modern OpenGL functions are loaded at runtime. Use the loader generated by GLAD.
		if (!gladLoadGL()) {
			std::cerr << "Failed to initialize GLAD (OpenGL)!" << std::endl;
			std::exit(-1);
		}
	}

	void LabApplication::runEventLoop()
	{
		onInit();

		bool running = true;
		while (running)
		{
			while (const std::optional event = window.pollEvent())
			{
				if (event->is<sf::Event::Closed>())
					running = false;
				else if (const auto* resized = event->getIf<sf::Event::Resized>())
					glViewport(0, 0, resized->size.x, resized->size.y);
			}

			float t = t_clock.getElapsedTime().asSeconds();
			float dt = dt_clock.getElapsedTime().asSeconds();
			dt_clock.restart();

			onUpdate(t, dt);
			onDraw(t, dt);

			window.display();
		}

		onExit();
	}

	void LabApplication::run(sf::Vector2u windowSize, const sf::String& windowTitle)
	{
		initializeWindowAndGraphics(windowSize, windowTitle);
		runEventLoop();
	}
}